moussaka/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('myrecipes.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

myrecipes/urls.py
from django.urls import path

from . import views

app_name = 'myrecipes'
urlpatterns = [
    # ex: /
    path('', views.IndexView.as_view(), name='index'),
    # ex: /5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /5/vote/
    path('<int:recipe_id>/rate/', views.rate, name='rate'),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

myrecipes/models.py
import datetime

from django.db import models
from django.utils import timezone


STAR_CHOICES = (
    (5, '*****'),
    (4, '****'),
    (3, '***'),
    (2, '**'),
    (1, '*'),
)


class Recipe(models.Model):
    title = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.title

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Step(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    step_text = models.TextField(max_length=1000)
    order = models.IntegerField(default=0)

    def __str__(self):
        return self.step_text


class Ingredient(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    ingredient_text = models.CharField(max_length=300)
    order = models.IntegerField(default=0)

    def __str__(self):
        return self.ingredient_text


class Rating(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    user = models.CharField(max_length=200)
    stars = models.IntegerField(choices=STAR_CHOICES, default=5)
    comment = models.TextField(max_length=1000, default=None, blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user + ": " + str(self.stars) + " stars"

polls/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

myrecipes/forms.py
from django import forms
# from django.forms import Textarea

from .models import Rating


class RatingForm(forms.ModelForm):

    class Meta:
        model = Rating
        fields = ('user', 'stars', 'comment',)
#        widgets = {
#            'comment': Textarea(attrs={'cols': 40, 'rows': 10}),
#        }

myrecipes/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from myrecipes.forms import RatingForm
from .models import Recipe


class IndexView(generic.ListView):
    template_name = 'myrecipes/index.html'
    context_object_name = 'latest_recipe_list'

    def get_queryset(self):
        """
        Return the last five published recipes (not including those set to be
        published in the future).
        """
        return Recipe.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.edit.FormMixin, generic.DetailView):
    model = Recipe
    form_class = RatingForm
    template_name = 'myrecipes/detail.html'

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        context['rate'] = self.request.GET.get('rate')
        return context

    def get_queryset(self):
        """
        Excludes any recipes that aren't published yet.
        """
        return Recipe.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Recipe
    template_name = 'myrecipes/results.html'


def rate(request, recipe_id):
    recipe = get_object_or_404(Recipe, pk=recipe_id)
    form = RatingForm(request.POST)
    if form.is_valid():
        rating = form.save(commit=False)
        rating.date = timezone.now()
        rating.recipe = recipe
        rating.save()
        return HttpResponseRedirect(reverse('myrecipes:results', args=(recipe.id,)))
    else:
        return render(request, 'myrecipes/detail.html', {
            'recipe': recipe,
            'error_message': "You didn't add a rating.",
        })

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Question, Choice


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

myrecipes/templates/myrecipes/detail.html
<h1>{{ recipe.title }}</h1>
<h3>Ingredients</h3>
<ul>
    {% for ingredient in recipe.ingredient_set.all %}
        <li>{{ ingredient.ingredient_text }}</li>
    {% endfor %}
</ul>

<h3>Method</h3>
<ol>
    {% for step in recipe.step_set.all %}
        <li>{{ step.step_text }}</li>
    {% endfor %}
</ol>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{% if rate %}
<div style="background-color: lightgrey;">
<h3>Rate</h3>

<form action="{% url 'myrecipes:rate' recipe.id %}" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Send rating" />
    <a href="{% url 'myrecipes:detail' recipe.id %}">[Hide form]</a>
    <a href="{% url 'myrecipes:results' recipe.id %}">[See results]</a>
</form>
</div>
{% else %}
    <div style="background-color: lightgrey;">
        <a href="{% url 'myrecipes:detail' recipe.id %}?rate=True">Rate</a>
        <a href="{% url 'myrecipes:results' recipe.id %}">[See results]</a>
    </div>
{% endif %}
<a href="{% url 'myrecipes:index' %}">[Back to list]</a>

myrecipes/templates/myrecipes/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'myrecipes/style.css' %}" />
{% if latest_recipe_list %}
    <ul>
        {% for recipe in latest_recipe_list %}
            <li><a href="{% url 'myrecipes:detail' recipe.id %}">{{ recipe.title }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No recipes are available.</p>
{% endif %}

myrecipes/templates/myrecipes/results.html
<h1>{{ recipe.title }}</h1>

<ul>
    {% for rating in recipe.rating_set.all %}
        <li>{{ rating.user }} -- {{ rating.stars }} star{{ rating.stars|pluralize }} -- {{ rating.date }} -- {{ rating.comment }}</li>
    {% endfor %}
</ul>

<a href="{% url 'myrecipes:detail' recipe.id %}?rate=True">Rate again?</a>

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
    {% endfor %}
    <input type="submit" value="Vote" />
</form>

polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>